add timeup edit

diff --git a/timeup b/timeup
--- a/timeup
+++ b/timeup
@@ -132,6 +132,14 @@ END
 	done
 }
 
+function log () {
+	_a=$(date --date=@"$2" +"%a %H:%M %d/%m")
+	_b=$(date --date=@"$3" +"%a %H:%M %d/%m")
+	diff=$(datediff "$2" "$3")
+	duration=$(showtime "$diff")
+	echo "$1, $_a to $_b for $duration"
+}
+
 if [ "$1" == 'stop' ]; then
 	if [ -f "$lockfile" ]; then
 		endtask
@@ -155,11 +163,7 @@ if [ "$1" == 'last' ]; then
 	_task=$(echo "$line" | cut -f1 -d' ')
 	_utc1=$(echo "$line" | cut -f2 -d' ')
 	_utc2=$(echo "$line" | cut -f3 -d' ')
-	_a=$(date --date=@"$_utc1" +"%a %H:%M %d/%m")
-	_b=$(date --date=@"$_utc2" +"%a %H:%M %d/%m")
-	diff=$(datediff "$_utc1" "$_utc2")
-	duration=$(showtime "$diff")
-	echo "last task was $_task, $_a to $_b for $duration"
+	log "$_task" "$_utc1" "$_utc2"
 	exit 0
 fi
 
@@ -176,6 +180,28 @@ if [ "$1" == 'track' ]; then
 	fi
 
 	track "$2" "$a" "$b"
+	exit 0
+fi
+
+if [ "$1" == 'edit' ]; then
+	line=$(<"$histfile" tail -n1)
+	_task=$(echo "$line" | cut -f1 -d' ')
+	_utc2=$(echo "$line" | cut -f3 -d' ')
+
+	if [ "$#" -eq 2 ]; then
+		tmp=$(date --date=@"$_utc2")
+		a=$(date --date="$tmp-$2" +%s)
+		b="$_utc2"
+	elif [ "$#" -eq 3 ]; then
+		a=$(date --date="$2" +%s)
+		b=$(date --date="$3" +%s)
+	else
+		echo 'Invalid arguments'
+		exit 1
+	fi
+
+	sed -i '$ d' "$histfile"
+	track "$_task" "$a" "$b"
 	exit 0
 fi
 
